id: P010481
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:52:03.583150
source_metadata:
  id: bdr:W3CN4909
  title: མནར་གཅོད་ཀྱི་ལང་ཚོ།
  author: ''
  volumes:
    6996e73e602c4b18b90cd14336993b9b:
      image_group_id: I3CN8669
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
